Merged in aj/SALM-388 (pull request #6287)
Check disk space before creating blockfile 

Recently multiple conversions in the nitro converter were failing because the converter could not create the read-only blockfile. This was occurring because the converter was running out of memory. Add a check in the configure script to check disk space available before creating blockfile.

Approved-by: daniel@fortanix.com

diff --git a/tools/container-converter/src/resources/fs/configure b/tools/container-converter/src/resources/fs/configure
--- a/tools/container-converter/src/resources/fs/configure
+++ b/tools/container-converter/src/resources/fs/configure
@@ -37,6 +37,13 @@ size_mb_up=$(awk -v n=$size_mb -v d=1 'BEGIN{print int(((n * 2)+d/2)/d) * d}')
 
 file_offset=$(( size_mb_up*1024*1024 ))
 
+# Check if the system has enough space to create and populate the blockfile
+blockfile_parent=$(dirname $BLOCKFILE)
+available_disk_space=$( df -B 1M $blockfile_parent | awk 'NR==2 {print $4}' )
+if [ $available_disk_space -lt $size_mb_up ]
+ then echo "Available disk space:" $available_disk_space  "Required disk space:" $size_mb_up; exit 1
+ else echo "Enough space available"
+fi
 
 # This creates a 1GB block file for the filesystem.
 dd if=/dev/zero of=$BLOCKFILE bs=1M count=${size_mb_up}
